"""Pydantic models for UniFi MCP server."""

from unifi_mcp.models.analysis import (
    CapacityReport,
    ConflictingClient,
    DeviceCapacity,
    DeviceFirmwareInfo,
    FirmwareRecommendation,
    FirmwareSecurityReport,
    FirmwareStatus,
    IPConflict,
    IPConflictReport,
    KnownVulnerability,
    LACPState,
    LAGGroup,
    LAGHealthReport,
    LAGMember,
    LAGStatus,
    LinkQualityReport,
    MACAlert,
    MACAlertSeverity,
    MACAlertType,
    MACAnalysisReport,
    MACFlappingEvent,
    MACTableEntry,
    PortLinkQuality,
    PortMACCount,
    PortQoSConfig,
    PortTrafficMetrics,
    PortVLANConfig,
    QoSFinding,
    QoSSeverity,
    QoSValidationReport,
    StormDetectionReport,
    StormEvent,
    StormSeverity,
    StormType,
    UpdatePriority,
    VLANDiagnosticCheck,
    VLANDiagnosticReport,
    VLANInfo,
)
from unifi_mcp.models.device import Device
from unifi_mcp.models.firewall import FirewallRule
from unifi_mcp.models.mirror import (
    DeviceMirrorCapabilities,
    MirrorCapability,
    MirrorReport,
    MirrorSession,
    MirrorSessionResult,
)
from unifi_mcp.models.network_path import NetworkPath, PathHop
from unifi_mcp.models.port import Port
from unifi_mcp.models.vlan import VLAN


__all__ = [
    # Analysis models
    'CapacityReport',
    'ConflictingClient',
    'DeviceCapacity',
    'DeviceFirmwareInfo',
    'FirmwareRecommendation',
    'FirmwareSecurityReport',
    'FirmwareStatus',
    'IPConflict',
    'IPConflictReport',
    'KnownVulnerability',
    'LACPState',
    'LAGGroup',
    'LAGHealthReport',
    'LAGMember',
    'LAGStatus',
    'LinkQualityReport',
    'MACAlert',
    'MACAlertSeverity',
    'MACAlertType',
    'MACAnalysisReport',
    'MACFlappingEvent',
    'MACTableEntry',
    'PortLinkQuality',
    'PortMACCount',
    'PortQoSConfig',
    'PortTrafficMetrics',
    'PortVLANConfig',
    'QoSFinding',
    'QoSSeverity',
    'QoSValidationReport',
    'StormDetectionReport',
    'StormEvent',
    'StormSeverity',
    'StormType',
    'UpdatePriority',
    'VLANDiagnosticCheck',
    'VLANDiagnosticReport',
    'VLANInfo',
    # Core models
    'Device',
    'DeviceMirrorCapabilities',
    'FirewallRule',
    'MirrorCapability',
    'MirrorReport',
    'MirrorSession',
    'MirrorSessionResult',
    'NetworkPath',
    'PathHop',
    'Port',
    'VLAN',
]
