"""Pydantic models for UniFi MCP server."""

from unifi_mapper.core.models.analysis import (
    CapacityReport,
    ConflictingClient,
    DeviceCapacity,
    DeviceFirmwareInfo,
    FirmwareRecommendation,
    FirmwareSecurityReport,
    FirmwareStatus,
    IPConflict,
    IPConflictReport,
    KnownVulnerability,
    LACPState,
    LAGGroup,
    LAGHealthReport,
    LAGMember,
    LAGStatus,
    LinkQualityReport,
    MACAlert,
    MACAlertSeverity,
    MACAlertType,
    MACAnalysisReport,
    MACFlappingEvent,
    MACTableEntry,
    PortLinkQuality,
    PortMACCount,
    PortQoSConfig,
    PortTrafficMetrics,
    PortVLANConfig,
    QoSFinding,
    QoSSeverity,
    QoSValidationReport,
    StormDetectionReport,
    StormEvent,
    StormSeverity,
    StormType,
    UpdatePriority,
    VLANDiagnosticCheck,
    VLANDiagnosticReport,
    VLANInfo,
)
from unifi_mapper.core.models.device import Device
from unifi_mapper.core.models.firewall import FirewallRule
from unifi_mapper.core.models.mirror import (
    DeviceMirrorCapabilities,
    MirrorCapability,
    MirrorReport,
    MirrorSession,
    MirrorSessionResult,
)
from unifi_mapper.core.models.network_path import NetworkPath, PathHop
from unifi_mapper.core.models.port import Port
from unifi_mapper.core.models.vlan import VLAN


__all__ = [
    # Analysis models
    'CapacityReport',
    'ConflictingClient',
    'DeviceCapacity',
    'DeviceFirmwareInfo',
    'FirmwareRecommendation',
    'FirmwareSecurityReport',
    'FirmwareStatus',
    'IPConflict',
    'IPConflictReport',
    'KnownVulnerability',
    'LACPState',
    'LAGGroup',
    'LAGHealthReport',
    'LAGMember',
    'LAGStatus',
    'LinkQualityReport',
    'MACAlert',
    'MACAlertSeverity',
    'MACAlertType',
    'MACAnalysisReport',
    'MACFlappingEvent',
    'MACTableEntry',
    'PortLinkQuality',
    'PortMACCount',
    'PortQoSConfig',
    'PortTrafficMetrics',
    'PortVLANConfig',
    'QoSFinding',
    'QoSSeverity',
    'QoSValidationReport',
    'StormDetectionReport',
    'StormEvent',
    'StormSeverity',
    'StormType',
    'UpdatePriority',
    'VLANDiagnosticCheck',
    'VLANDiagnosticReport',
    'VLANInfo',
    # Core models
    'Device',
    'DeviceMirrorCapabilities',
    'FirewallRule',
    'MirrorCapability',
    'MirrorReport',
    'MirrorSession',
    'MirrorSessionResult',
    'NetworkPath',
    'PathHop',
    'Port',
    'VLAN',
]
